### ISSUE TITLE
matchDir option didn't work

### ISSUE THREAD

**Issue by 0q0** [fshost/node-dir#28] opened 2015-11-03 07:19 UTC
The *matchDir* option has no effect but the *excludeDir* option works well in my same project.

**Comment by fshost** [comment] 2016-05-05 23:43
There is a test for the matchDir option which passes. Can you give more details as to how specifically the matchDir option is failing for you?

**Comment by fshost** [comment] 2016-06-28 08:05
AFAIK the matcher option works, there is a test for it that passes. Due to the time passed on this issue I'm closing it. If someone can provide updated details that can help in replicating the error I'll reopen it.

**Closed by fshost** 2016-06-28 08:05 UTC

**Comment by octopuss** [comment] 2016-07-27 07:24
I think that I can reproduce it. Imagine structure like this
```
/folder/file.txt
/folder/included/.....
folder/excluded/...
````
In this case having option `matchDir` set to `included` is applied only when entry is a directory (see https://github.com/fshost/node-dir/blob/master/lib/readfilesstream.js#L94). `file.txt` is added to the result although it is not in the `matchDir`.
